---
- hosts: all
  become: yes

  vars:
    yolo_location: "/Devops/yolo_app"
    github_repo: "https://github.com/Marsh-sudo/yolo"

  roles:
    - nodejs
    - backend
    - client


  tasks:
    - name: Install required packages
      apt:
        name: ['git', 'curl']
        state: present
        update_cache: yes

    - name: Clone the code from GitHub
      git:
        repo: "{{ github_repo }}"
        dest: "{{ yolo_location }}"
        clone: yes

    - name: Ensure yolo project exists
      file: "path={{ yolo_location }} state=directory"


    - name: Start Docker Compose
      command: "docker-compose -f {{ yolo_location }}/docker-compose.yml up -d"
      tags:
        - docker_compose