---
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  pre_tasks:
  - name: Install EPEL repo.
      yum: name=epel-release state=present

  - name: Import Remi GPG key.
      rpm_key:
        key: "https://rpms.remirepo.net/RPM-GPG-KEY-remi"
        state: present

  - name: Install Remi repo.
      yum:
        name: "https://rpms.remirepo.net/enterprise/remi-release-7.rpm"
        state: present

  tasks:
  - name: Ensure yolo project exists
    file: "path={{ node_apps_location }} state=directory"

  - name: Copy yolo project to the server
    copy:
      src: "{{ item }}"
      dest: "{{ node_apps_location }}/{{ item }}"
    with_items:
      - client/
      - backend/
      - docker-compose.yml
      
  - name: Ensure client docker image is built from the client folder
    docker_image:
      name: client
      source: build
      build: 
        path: client
      state: present

  - name: Ensure the client container is running.
    docker_container:
      image: client:latest
      name: client
      state: started

  - name: Ensure backend docker image is built from the backend folder
    docker_image:
      name: backend
      source: build
      build: 
        path: backend
      state: present