version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    restart: "always"
    depends_on:
      - backend
    networks:
      - yoloProduct
    # volumes:
    #   - /app/node_modules:/app/node_modules # for caching node modules in
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: "always"
    networks:
      - yoloProduct
    volumes:
      - backend_mongodb_data:/data/db


networks:
  yoloProduct:

volumes:
  backend_mongodb_data:
      