apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-mongo-express
  labels:
    app: mongo-backend-express
spec:
  selector:
    matchLabels:
      app: mongo-backend-express
  template:
    metadata:
      labels:
        app: mongo-backend-express
    spec:
      containers:
      - name: yolo-mongodb-express
        image: mongo-express
        ports:
          - containerPort: 8090
        env:
          - name: MONGO_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-username
          - name: MONGO_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-password
          - name: MONGODBEXPRESS_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongo-backend-express
  type: LoadBalancer
  ports:
  - port: 8050
    targetPort: 8050
