apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-deployment
  labels:
    app: yolo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app
  template:
    metadata:
      labels:
        app: yolo-app
    spec:
      containers:
      - name: yoloclient
        image: marshkelvin0/client:1.0.0
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
      - name: yolobackend
        image: marshkelvin0/backend:1.0.1
        volumeMounts:
            - name: backend-persistent-storage
              mountPath: /data/db
        ports:
          - containerPort: 5000
      volumes:
      - name: backend-persistent-storage
        persistentVolumeClaim:
            claimName: mongodb-pvc  # Use your PVC name here
      - name: mongodb
        image: mongo:latest
        ports:
          - containerPort: 27018
        env:
          - name: MONGO_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-username
          - name: MONGO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongodb-password
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-app-service
spec:
  selector:
    app: yolo-app
  type: LoadBalancer
  ports:
  - port: 3005
    targetPort: 3005
    protocal: TCP

