apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-deployments
  labels:
    app: yolo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app-deployments
  template:
    metadata:
      labels:
        app: yolo-app-deployments
    spec:
      containers:
      - name: yoloclient
      # labels:
      #   app: yolo-app
        image: marshkelvin0/client
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
      - name: yolobackend
        image: marshkelvin0/backend
          # resources:
          # limits:
          #   memory: "128Mi"
          #   cpu: "500m"
        ports:
          - containerPort: 5000
