apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-app-deployment
  labels:
    app: yolo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-app-deployment
  template:
    metadata:
      labels:
        app: yolo-app-deployment
    spec:
      containers:
      - name: yoloclient
      # labels:
      #   app: yolo-app
        image: marshkelvin0/client
        ports:
        - containerPort: 3000
          protocol: TCP
          name: http
      - name: yolobackend
        image: marshkelvin0/backend 
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-app-service
spec:
  selector:
    app: yolo-app-deployment
  ports:
  - port: 3000
    targetPort: 3000

