apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 10Gi  # Specify the desired storage size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: manual  
  gcePersistentDisk:
    pdName: yolo-app  # Name of the Persistent Disk created
    fsType: ext4 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Should match the PV capacity
  storageClassName: manual  # Should match the PV storageClassName
