---
- name: Update apt cache
  apt:
    update_cache: yes
    
- name: Install Node.js (npm plus all its dependencies).
  apt: name=npm state=present

- name: Install forever module (to run our Node.js app).
  npm: name=forever global=yes state=present